apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-v2
  namespace: default
spec:
  replicas: 4 # Number of replicas
  selector:
    matchLabels:
      app: myapp-v2
  template:
    metadata:
      labels:
        app: myapp-v2
    spec:
      containers:
        - name: myapp-v1
          image: surya9961/javacalculator:v1
          ports:
            - containerPort: 8081  # Port 8081
