apiVersion: v1
kind: Service
metadata:
  name: myapp2-service
spec:
  type: LoadBalancer
  selector:
    app: myapp-v2
  ports:
  - protocol: TCP
    port: 80        # This is the port exposed to the outside world
    targetPort: 8081
